### ISSUE TITLE
Solving environment: failed

### ISSUE THREAD

**Issue by hanxuelian** [Oshlack/ALLSorts#1]
conda env create -f env/allsorts.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - libgfortran=3.0.1

**Comment by breons** [comment]
Apologies for the delay, I've been on leave.

The most recent commit includes a stripped down allsorts.yml file which should resolve your issue and will allow you to proceed with the installation. Please let me know if you run into any other issues.

**Comment by hanxuelian** [comment]
> Apologies for the delay, I've been on leave.
> 
> The most recent commit includes a stripped down allsorts.yml file which should resolve your issue and will allow you to proceed with the installation. Please let me know if you run into any other issues.

**Comment by hanxuelian** [comment]
> Apologies for the delay, I've been on leave.
> 
> The most recent commit includes a stripped down allsorts.yml file which should resolve your issue and will allow you to proceed with the installation. Please let me know if you run into any other issues.

Successfully resolved, thank you very much

**Comment by breons** [comment]
Wonderful! Let me know if you need anything else.
