### ISSUE TITLE
ALLSorts test failed 

### ISSUE THREAD

**Issue by baharvand79** [Oshlack/ALLSorts#12]
Hello,
I am trying to run the test. However, it fails.
I am getting this error after running 
`python ALLSorts -samples tests/counts/test_counts.csv -destination ../test_results`

> Traceback (most recent call last):
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/errors.py", line 823, in new_error_context
>     yield
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/lowering.py", line 293, in lower_block
>     self.lower_inst(inst)
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/lowering.py", line 438, in lower_inst
>     val = self.lower_assign(ty, inst)
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/lowering.py", line 624, in lower_assign
>     return self.lower_expr(ty, value)
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/lowering.py", line 1159, in lower_expr
>     res = self.lower_call(resty, expr)
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/lowering.py", line 889, in lower_call
>     res = self._lower_call_normal(fnty, expr, signature)
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/lowering.py", line 1130, in _lower_call_normal
>     res = impl(self.builder, argvals, self.loc)
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/base.py", line 1201, in __call__
>     res = self._imp(self._context, builder, self._sig, args, loc=loc)
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/base.py", line 1231, in wrapper
>     return fn(*args, **kwargs)
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/cpython/rangeobj.py", line 40, in range1_impl
>     state.stop = stop
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/cgutils.py", line 164, in __setattr__
>     self[self._datamodel.get_field_position(field)] = value
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/cgutils.py", line 188, in __setitem__
>     raise TypeError("Invalid store of {value.type} to "
> TypeError: Invalid store of i64 to i32 in <numba.core.datamodel.models.RangeModel object at 0x7f5e01cb5d30> (trying to write member #1)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/root/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/root/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/root/ALLSorts/ALLSorts/ALLSorts/__main__.py", line 13, in <module>
>     import allsorts
>   File "/root/ALLSorts/ALLSorts/ALLSorts/allsorts.py", line 33, in <module>
>     from ALLSorts.operations.comparisons import rebuild_comparisons
>   File "/root/anaconda3/lib/python3.9/site-packages/ALLSorts/operations/comparisons.py", line 20, in <module>
>     from umap import UMAP
>   File "/root/anaconda3/lib/python3.9/site-packages/umap/__init__.py", line 1, in <module>
>     from .umap_ import UMAP
>   File "/root/anaconda3/lib/python3.9/site-packages/umap/umap_.py", line 54, in <module>
>     from umap.layouts import (
>   File "/root/anaconda3/lib/python3.9/site-packages/umap/layouts.py", line 39, in <module>
>     def rdist(x, y):
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/decorators.py", line 219, in wrapper
>     disp.compile(sig)
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/dispatcher.py", line 965, in compile
>     cres = self._compiler.compile(args, return_type)
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/dispatcher.py", line 125, in compile
>     status, retval = self._compile_cached(args, return_type)
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/dispatcher.py", line 139, in _compile_cached
>     retval = self._compile_core(args, return_type)
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/dispatcher.py", line 152, in _compile_core
>     cres = compiler.compile_extra(self.targetdescr.typing_context,
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/compiler.py", line 693, in compile_extra
>     return pipeline.compile_extra(func)
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/compiler.py", line 429, in compile_extra
>     return self._compile_bytecode()
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/compiler.py", line 497, in _compile_bytecode
>     return self._compile_core()
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/compiler.py", line 476, in _compile_core
>     raise e
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/compiler.py", line 463, in _compile_core
>     pm.run(self.state)
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 353, in run
>     raise patched_exception
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 341, in run
>     self._runPass(idx, pass_inst, state)
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
>     return func(*args, **kwargs)
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 296, in _runPass
>     mutated |= check(pss.run_pass, internal_state)
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 269, in check
>     mangled = func(compiler_state)
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/typed_passes.py", line 394, in run_pass
>     lower.lower()
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/lowering.py", line 196, in lower
>     self.lower_normal_function(self.fndesc)
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/lowering.py", line 250, in lower_normal_function
>     entry_block_tail = self.lower_function_body()
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/lowering.py", line 279, in lower_function_body
>     self.lower_block(block)
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/lowering.py", line 293, in lower_block
>     self.lower_inst(inst)
>   File "/root/anaconda3/lib/python3.9/contextlib.py", line 137, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "/root/anaconda3/lib/python3.9/site-packages/numba/core/errors.py", line 837, in new_error_context
>     raise newerr.with_traceback(tb)
> numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: native lowering)
> Invalid store of i64 to i32 in <numba.core.datamodel.models.RangeModel object at 0x7f5e01cb5d30> (trying to write member #1)
> 
> File "../../anaconda3/lib/python3.9/site-packages/umap/layouts.py", line 53:
> def rdist(x, y):
>     <source elided>
>     dim = x.shape[0]
>     for i in range(dim):
>     ^
> 
> During: lowering "$20call_function.7 = call $16load_global.5(dim, func=$16load_global.5, args=[Var(dim, layouts.py:52)], kws=(), vararg=None, target=None)" at /root/anaconda3/lib/python3.9/site-packages/umap/layouts.py (53)

I saw this issue #6  , but the solution didn't work for me.  I installed numba version 50.1. Then I did the commands below:
```
git pull
git checkout dev-0.2.1
pip install .
```
But I am getting this error:

> Processing /root/ALLSorts/ALLSorts
>   DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
>    pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
> Requirement already satisfied: joblib==0.15.1 in /root/anaconda3/lib/python3.9/site-packages (from ALLSorts==0.2.1) (0.15.1)
> Requirement already satisfied: matplotlib==3.2.1 in /root/anaconda3/lib/python3.9/site-packages (from ALLSorts==0.2.1) (3.2.1)
> Collecting numpy==1.18.1
>   Downloading numpy-1.18.1.zip (5.4 MB)
>      |████████████████████████████████| 5.4 MB 4.6 MB/s
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>     Preparing wheel metadata ... error
>     ERROR: Command errored out with exit status 1:
>      command: /root/anaconda3/bin/python /root/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp5ingp282
>          cwd: /tmp/pip-install-ygm9kgh0/numpy_1d1b7c7f0a6f48f3ad7a7dda6202d35a
>     Complete output (24 lines):
>     Running from numpy source directory.
>     <string>:461: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
>     Traceback (most recent call last):
>       File "/root/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
>         main()
>       File "/root/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
>         json_out['return_val'] = hook(**hook_input['kwargs'])
>       File "/root/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 151, in prepare_metadata_for_build_wheel
>         return hook(metadata_directory, config_settings)
>       File "/tmp/pip-build-env-e6ctoqd_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
>         self.run_setup()
>       File "/tmp/pip-build-env-e6ctoqd_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 482, in run_setup
>         super(_BuildMetaLegacyBackend,
>       File "/tmp/pip-build-env-e6ctoqd_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
>         exec(code, locals())
>       File "<string>", line 488, in <module>
>       File "<string>", line 465, in setup_package
>       File "/tmp/pip-install-ygm9kgh0/numpy_1d1b7c7f0a6f48f3ad7a7dda6202d35a/numpy/distutils/core.py", line 26, in <module>
>         from numpy.distutils.command import config, config_compiler, \      File "/tmp/pip-install-ygm9kgh0/numpy_1d1b7c7f0a6f48f3ad7a7dda6202d35a/numpy/distutils/command/config.py", line 20, in <module>
>         from numpy.distutils.mingw32ccompiler import generate_manifest      File "/tmp/pip-install-ygm9kgh0/numpy_1d1b7c7f0a6f48f3ad7a7dda6202d35a/numpy/distutils/mingw32ccompiler.py", line 34, in <module>
>         from distutils.msvccompiler import get_build_version as get_build_msvc_version
>     ModuleNotFoundError: No module named 'distutils.msvccompiler'
>     ----------------------------------------
> WARNING: Discarding https://files.pythonhosted.org/packages/40/de/0ea5092b8bfd2e3aa6fdbb2e499a9f9adf810992884d414defc1573dca3f/numpy-1.18.1.zip#sha256=b6ff59cee96b454516e47e7721098e6ceebef435e3e21ac2d6c3b8b02628eb77 (from https://pypi.org/simple/numpy/) (requires-python:>=3.5). Command errored out with exit status 1: /root/anaconda3/bin/python /root/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp5ingp282 Check the logs for full command output.
> ERROR: Could not find a version that satisfies the requirement numpy==1.18.1 (from allsorts) (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0rc1, 1.15.0rc2, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0rc1, 1.16.0rc2, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0rc1, 1.17.0rc2, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0rc1, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0rc1, 1.19.0rc2, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.20.0rc1, 1.20.0rc2, 1.20.0, 1.20.1, 1.20.2, 1.20.3, 1.21.0rc1, 1.21.0rc2, 1.21.0, 1.21.1, 1.21.2, 1.21.3, 1.21.4, 1.21.5, 1.21.6, 1.22.0rc1, 1.22.0rc2, 1.22.0rc3, 1.22.0, 1.22.1, 1.22.2, 1.22.3, 1.22.4, 1.23.0rc1, 1.23.0rc2, 1.23.0rc3, 1.23.0, 1.23.1, 1.23.2)
> ERROR: No matching distribution found for numpy==1.18.1

My packages are:

> (allsorts) ➜  ALLSorts git:(master) ✗ conda list
> # packages in environment at /root/anaconda3/envs/allsorts:
> #
> # Name                    Version                   Build  Channel
> _libgcc_mutex             0.1                        main    anaconda
> _openmp_mutex             5.1                       1_gnu    anaconda
> blas                      1.0                         mkl    anaconda
> ca-certificates           2022.4.26            h06a4308_0    anaconda
> certifi                   2022.6.15        py38h06a4308_0    anaconda
> cycler                    0.11.0             pyhd3eb1b0_0    anaconda
> dbus                      1.13.18              hb2f20db_0    anaconda
> expat                     2.4.4                h295c915_0    anaconda
> fontconfig                2.13.1               h6c09931_0    anaconda
> freetype                  2.11.0               h70c0345_0    anaconda
> glib                      2.56.2               hd408876_0    anaconda
> gst-plugins-base          1.14.0               hbbd80ab_1    anaconda
> gstreamer                 1.14.0               hb453b48_1    anaconda
> icu                       58.2                 he6710b0_3    anaconda
> intel-openmp              2022.0.1          h06a4308_3633    anaconda
> joblib                    0.15.1                     py_0    anaconda
> jpeg                      9e                   h7f8727e_0    anaconda
> kiwisolver                1.4.2            py38h295c915_0    anaconda
> ld_impl_linux-64          2.38                 h1181459_1    anaconda
> libffi                    3.3                  he6710b0_2    anaconda
> libgcc-ng                 11.2.0               h1234567_1    anaconda
> libgfortran-ng            7.5.0               ha8ba4b0_17    anaconda
> libgfortran4              7.5.0               ha8ba4b0_17    anaconda
> libgomp                   11.2.0               h1234567_1    anaconda
> libllvm10                 10.0.1               hbcb73fb_5    anaconda
> libpng                    1.6.37               hbc83047_0    anaconda
> libstdcxx-ng              11.2.0               h1234567_1    anaconda
> libuuid                   1.0.3                h7f8727e_2    anaconda
> libxcb                    1.15                 h7f8727e_0    anaconda
> libxml2                   2.9.14               h74e7548_0    anaconda
> llvmlite                  0.36.0           py38h612dafd_4    anaconda
> matplotlib                3.2.1                         0    anaconda
> matplotlib-base           3.2.1            py38hef1b27d_0    anaconda
> mkl                       2019.4                      243    anaconda
> mkl-service               2.3.0            py38he904b0f_0    anaconda
> mkl_fft                   1.3.0            py38h54f3939_0    anaconda
> mkl_random                1.1.0            py38h962f231_0    anaconda
> ncurses                   6.3                  h7f8727e_2    anaconda
> numba                     0.53.1           py38ha9443f7_0    anaconda
> numpy                     1.18.1           py38h4f9e942_0    anaconda
> numpy-base                1.18.1           py38hde5b4d6_1    anaconda
> openssl                   1.1.1o               h7f8727e_0    anaconda
> packaging                 21.3               pyhd3eb1b0_0    anaconda
> pandas                    1.0.3            py38h0573a6f_0    anaconda
> pcre                      8.45                 h295c915_0    anaconda
> pip                       20.0.2                   py38_3    anaconda
> plotly                    4.14.3             pyhd3eb1b0_0    anaconda
> pyparsing                 3.0.4              pyhd3eb1b0_0    anaconda
> pyqt                      5.9.2            py38h05f1152_4    anaconda
> python                    3.8.3                hcff3b4d_2    anaconda
> python-dateutil           2.8.2              pyhd3eb1b0_0    anaconda
> python_abi                3.8                      2_cp38    conda-forge
> pytz                      2022.1           py38h06a4308_0    anaconda
> qt                        5.9.7                h5867ecd_1    anaconda
> readline                  8.1.2                h7f8727e_1    anaconda
> retrying                  1.3.3              pyhd3eb1b0_2    anaconda
> scikit-learn              0.22.1           py38hd81dba3_0    anaconda
> scipy                     1.4.1            py38h0b6359f_0    anaconda
> setuptools                46.4.0                   py38_0    anaconda
> sip                       6.5.1            py38h295c915_0    anaconda
> six                       1.16.0             pyhd3eb1b0_1    anaconda
> sqlite                    3.38.5               hc218d9a_0    anaconda
> tbb                       2020.3               hfd86e86_0    anaconda

I am using conda 4.13.0 and Python 3.9.12.
I am using Ubuntu terminal environment with WSL.

Any help is greatly appreciated.
Thanks,
Shakiba
> tk                        8.6.12               h1ccaba5_0    anaconda
> toml                      0.10.2             pyhd3eb1b0_0    anaconda
> tornado                   6.1              py38h27cfd23_0    anaconda
> umap-learn                0.4.4            py38h32f6830_0    conda-forge
> wheel                     0.37.1             pyhd3eb1b0_0    anaconda
> xz                        5.2.5                h7f8727e_1    anaconda
> zlib                      1.2.12               h7f8727e_2    anaconda

**Comment by monovich** [comment]
Just wanted to chime in with a solution that worked for me. Searching this error seems to indicate there's issues with `umap-learn 0.4.4`. Running  `conda install -c conda-forge umap-learn` in the `allsorts` environment should update you to at least `umap-learn-0.5.3` and let you run the ALLSorts tests.
